#!/bin/zsh
function foo {
    echo "x at start of function = ${x}"
    local x="world hello"
    echo "x at end of function = ${x}"
}

x="hello world"
echo "x before function = ${x}"
foo
echo "x after function = ${x}"